# Generated by Django 5.2.11 on 2026-02-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.CharField(choices=[('light', 'Светлая'), ('dark', 'Темная')], default='light', max_length=10),
        ),
    ]
