# Generated by Django 5.2.11 on 2026-02-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='parsed_time',
            field=models.DateField(),
        ),
    ]
