# Generated by Django 5.2.11 on 2026-02-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_alter_rate_parsed_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='rate',
            name='delta',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='parsed_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='today',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rate',
            name='tomorrow',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterModelTable(
            name='rate',
            table='rates',
        ),
    ]
