# Generated by Django 5.2.11 on 2026-02-22 21:30

from django.db import migrations, models


def add_shaurma_currency(apps, schema_editor):
    """Добавляет валюту ШАУРМА с постоянным курсом 250 рублей."""
    Rate = apps.get_model('rates', 'Rate')
    # Создаём записи для всех времён (Шаурма всегда стоит 250 рублей!)
    from datetime import datetime, timedelta
    
    # Создаём запись на сегодня
    Rate.objects.create(
        currency='ШАУРМА',
        today=250.0000,
        tomorrow=250.0000,
        delta=0.0000,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_remove_rate_created_at_alter_rate_delta_and_more'),
    ]

    operations = [
        # Сначала изменяем max_length для поля currency
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.CharField(
                max_length=10,
                verbose_name='Валюта',
                help_text='Код или название валюты (например, ДОЛЛАР, ЕВРО, ФУНТ, ШАУРМА)'
            ),
        ),
        # Затем добавляем данные для ШАУРМЫ
        migrations.RunPython(add_shaurma_currency),
    ]